<Project Sdk="Uno.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net10.0-android;net10.0-ios;net10.0-windows10.0.26100;net10.0-browserwasm;net10.0-desktop</TargetFrameworks>

    <OutputType>Exe</OutputType>
    <UnoSingleProject>true</UnoSingleProject>

    <!-- Display name -->
    <ApplicationTitle>Symptum</ApplicationTitle>
    <!-- App Identifier -->
    <ApplicationId>com.symptum.app</ApplicationId>
    <!-- Versions -->
    <ApplicationDisplayVersion>0.0.6</ApplicationDisplayVersion>
    <ApplicationVersion>1</ApplicationVersion>
    <AndroidPackageFormat>apk</AndroidPackageFormat>
    <!-- Package Publisher -->
    <ApplicationPublisher>Symptum Community</ApplicationPublisher>
    <!-- Package Description -->
    <Description>Symptum Application.</Description>
    <!--
      If you encounter this error message:

        error NETSDK1148: A referenced assembly was compiled using a newer version of Microsoft.Windows.SDK.NET.dll.
        Please update to a newer .NET SDK in order to reference this assembly.

      This means that the two packages below must be aligned with the "build" version number of
      the "Microsoft.Windows.SDK.BuildTools" package above, and the "revision" version number
      must be the highest found in https://www.nuget.org/packages/Microsoft.Windows.SDK.NET.Ref.
    -->
    <!-- <WindowsSdkPackageVersion>10.0.22621.28</WindowsSdkPackageVersion> -->

    <!--
      UnoFeatures are used to quickly add and manage features enabled for your app.
      https://aka.platform.uno/singleproject-features
    -->
    <UnoFeatures>
      Lottie;
      <!-- MediaElement; -->
      Toolkit;
      Mvvm;
      ExtensionsCore;
      ThemeService;
      SkiaRenderer;
    </UnoFeatures>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Symptum.Common\Symptum.Common.csproj" />
    <ProjectReference Include="..\Symptum.Core\Symptum.Core.csproj" />
    <ProjectReference Include="..\Symptum.UI\Symptum.UI.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" />
    <PackageReference Include="CommunityToolkit.WinUI.Controls.ColorPicker" />
    <PackageReference Include="CommunityToolkit.WinUI.Controls.Segmented" />
    <PackageReference Include="CommunityToolkit.WinUI.Controls.SettingsControls" />
  </ItemGroup>

  <PropertyGroup>
    <UnoIconBackgroundColor>Transparent</UnoIconBackgroundColor>
    <UnoIconBackgroundFile>$(MSBuildThisFileDirectory)Assets\Icons\icon_transparent.svg</UnoIconBackgroundFile>
    <UnoIconForegroundFile>$(MSBuildThisFileDirectory)Assets\Icons\icon_default.svg</UnoIconForegroundFile>
    <UnoIconForegroundScale>1</UnoIconForegroundScale>

    <UnoIconBackgroundFile Condition="'$(IsAndroid)' == 'true'">$(MSBuildThisFileDirectory)Assets\Icons\icon.svg</UnoIconBackgroundFile>
    <UnoIconForegroundFile Condition="'$(IsAndroid)' == 'true'">$(MSBuildThisFileDirectory)Assets\Icons\icon_foreground.svg</UnoIconForegroundFile>
    <UnoIconForegroundScale Condition="'$(IsAndroid)' == 'true'">0.4</UnoIconForegroundScale>

    <UnoSplashScreenFile>$(MSBuildThisFileDirectory)Assets\Splash\splash_screen.svg</UnoSplashScreenFile>
    <UnoSplashScreenBaseSize>1024,1024</UnoSplashScreenBaseSize>
    <UnoSplashScreenColor>#222222</UnoSplashScreenColor>
  </PropertyGroup>
</Project>
